# -*- coding: utf-8 -*-
"""ECG Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCHtSVN_lnfCSJxe35DNXv-sQxSQwwy-
"""

# Colab cell (code)
!pip install -q kaggle scikit-learn opencv-python joblib matplotlib tensorflow

# Colab cell (code)
from google.colab import files
files.upload()   # choose kaggle.json from your machine
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Colab cell (code) - downloads and unzips into /content
!kaggle datasets download -d drkhaledmohsin/national-heart-foundation-2023-ecg-dataset -p /content --unzip

# Colab cell (code)
import os
for p in os.listdir('ECG Data'):
    print(p)

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import joblib

dataset_path = "ECG Data"
img_size = (224, 224)

X = []
y = []

for label, folder in enumerate(os.listdir(dataset_path)):
    folder_path = os.path.join(dataset_path, folder)
    for file in os.listdir(folder_path):
        img_path = os.path.join(folder_path, file)
        img = cv2.imread(img_path)
        if img is not None:
            img = cv2.resize(img, img_size)
            img = img / 255.0
            X.append(img.flatten())
            y.append(label)

X = np.array(X)
y = np.array(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = SVC(kernel='linear')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

joblib.dump(model, "ecg_model.pkl")